[launcher]
task="onchain-bot"
jvm_args=[
    "-server",
    "-Xmx8192m"
]

[notarb]
acknowledge_terms_of_service=true

[user]
keypair_path="/path/to/your/key.json"
protect_keypair=false

[token_accounts_checker]
rpc_url="${DEFAULT_RPC_URL}"
delay_seconds=3

[blockhash_updater]
rpc_url="${DEFAULT_RPC_URL}"
delay_ms=200

[account_size_loader]
rpc_url="${DEFAULT_RPC_URL}"
invalid_account_size=200
buffer_size=1500

[market_loader]
rpc_url="${DEFAULT_RPC_URL}"

[lookup_table_loader]
rpc_url="${DEFAULT_RPC_URL}"

[transaction_executor]
threads=0

[[spam_rpc]]
id="my-super-duper-sender"
url="${DEFAULT_RPC_URL}"
max_idle_connections=1

# Disable local file loading, use URLs
[[markets_file]]
enabled=true
path="markets.json"
update_seconds=300

[[markets_url]]
enabled=false
url="https://notarb.org/markets.json"
update_seconds=300

[[lookup_tables_file]]
enabled=true
path="my-lookup-tables.json"
update_seconds=300

[[lookup_tables_url]]
enabled=false
url="https://notarb.org/lups.json"
update_seconds=300

[jito]
ips_file_path=""
prefunded_keypairs_path=""

[[jito.rpc]]
enabled=true
url="https://tokyo.mainnet.block-engine.jito.wtf"
id="jito-1"
uuid="9d10a340-d05b-11f0-917f-095444f46943"
regions=["singapore", "ny", "slc", "london", "frankfurt", "amsterdam", "tokyo"]

# --- Strategies ---

## SOL (Jito)
[[swap]]
enabled=true
mint="SOL"

[swap.strategy_defaults]
meteora_bin_limit=20

# Micro Strategy (Flash Loan Enabled)
[[swap.strategy]]
cu_limit=369_369
flash_loan=true
min_jito_tip_lamports=1000
max_jito_tip_lamports=2000
require_profit=true
min_profit_lamports=2000
cooldown_ms=1500

# Medium Strategy (0.01 - 0.03 SOL)
[[swap.strategy]]
min_spend=0.01
max_spend=0.03
cu_limit=369369
min_jito_tip_lamports=2000
max_jito_tip_lamports=5000